# Generated by Django 5.2 on 2025-05-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_ordemservicos'),
        ('funcionarios', '0001_initial'),
        ('servicos', '0004_alter_servico_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdemServicos',
            new_name='OrdemServico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(through='agendamentos.OrdemServico', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
