# Generated by Django 5.2 on 2025-05-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviços'},
        ),
    ]
