# Generated by Django 5.2 on 2025-05-12 23:22

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Serviços'},
        ),
    ]
