# Generated by Django 5.2 on 2025-05-19 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_alter_produtosservico_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosservico',
            name='servico',
            field=models.ForeignKey(help_text='Nome do serviço realizado', on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
